/// <reference path="../typings/tsd.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../objects/forest.ts" />
/// <reference path="../objects/enemy.ts" />
/// <reference path="../objects/bonus.ts" />
/// <reference path="../objects/gameobject.ts" />
/// <reference path="../objects/player.ts" />
/// <reference path="../managers/collision.ts" />
/// <reference path="../scenes/end.ts" />
/// <reference path="../scenes/play.ts" />
/// <reference path="../scenes/menu.ts" />
/// <reference path="../scenes/intro.ts" /> 
//# sourceMappingURL=_reference.js.map